services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=****
      - PGID=****
      - VERSION=latest
    volumes:
      - /dev/shm:/transcode
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /pathTo/yourMedia:/multimedia
    restart: unless-stopped