services:
  motioneye:
    image: ghcr.io/motioneye-project/motioneye:edge
    container_name: motioneye
    restart: unless-stopped
    hostname: [hostname]
    volumes: # [optional] assign other local storage if you want to save video recordings to a location beside the OS disk
      - /local/storage/motioneye:/var/lib/motioneye 
    ports:
      - 8765:8765