services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: [server name]
    environment:
      - PUID=[syncthing UID]
      - PGID=[syncthing GID]
    volumes:
      - /rootDir/ofYour/data:/var/syncthing
    network_mode: host
    restart: unless-stopped
    healthcheck:
      test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
      interval: 1m
      timeout: 10s
      retries: 3